### ISSUE TITLE
Cannot send DM from Coracle to Damus

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#1]
### client initiating action
Coracle

### client receiving end
Damus

### Timestamp
Jan 23, 2024

### What happens
I cannot send a DM from Coracle to Damus, as Coracle implements DM gift wrapping, whereas Damus does not. 
Coracle does call out the potential for other clients to not receive DMs from Coracle. Coracle does not explicitly call out Damus, or any other clients that may not be DM compatible.

### Suggestion

**Comment by staab** [comment]
Coracle gives you the option to send a legacy DM, are you not getting that dialog?

**Comment by alltheseas** [comment]
> Coracle gives you the option to send a legacy DM, are you not getting that dialog?

If I did receive this prompt, I did not notice it! I will revisit the flow.

**Comment by alltheseas** [comment]
> Coracle gives you the option to send a legacy DM, are you not getting that dialog?

Not seeing any dialogue on existing account. I do receive a notification about the new standard when I tap the 🔒 icon.


<img width="1424" alt="Screenshot 2024-01-26 at 9 38 34 PM" src="https://github.com/alltheseas/nostrability/assets/64376233/8db8b67a-e2c9-4609-b969-d2d103d9655c">

 Let me create another account

**Comment by alltheseas** [comment]
confirming I do not receive a prompt or option to revert to legacy DM

<img width="1424" alt="Screenshot 2024-01-26 at 9 42 03 PM" src="https://github.com/alltheseas/nostrability/assets/64376233/e418b16a-10dd-44f9-a503-d64e80304a13">

**Comment by alltheseas** [comment]
Confirming I don't see anything in Damus DMs or DM requests

**Comment by staab** [comment]
Ah, I see, it only prompts you if the most recent DM in the conversation was a legacy one, otherwise it assumes new-style. I'll look into improving this.

**Comment by staab** [comment]
This should be better in the next release of coracle. @alltheseas I'd welcome your feedback on dev.coracle.social

**Comment by alltheseas** [comment]
![image](https://github.com/nostrability/nostrability/assets/64376233/37fe82ce-2bba-4cc9-8e1a-c8f637ee20f9)

From damus received latter

**Comment by alltheseas** [comment]
Overall it's an improvement, as there is a chance and method that the user will be able to use to communicate with a legacy DM counterparty.

Ideally, there is some way to auto-detect which setting is needed for which counterparty, or there is NIP alignment.

I would place my energy on the former long term solution 😂

**Comment by alltheseas** [comment]
Recommend to close issue once you merge into main Coracle branch

**Comment by alltheseas** [comment]
Confirming that Coracle successfully receives replies from Damus

**Comment by staab** [comment]
> Ideally, there is some way to auto-detect which setting is needed for which counterparty

I'm hoping that won't be necessary, ideally other clients will migrate because nip 04 dms are truly terrible.

**Comment by alltheseas** [comment]
Agree it's not ideal. The part I am wary about with yall devs is the herding cats part. Will has another idea of how to improve DMs, and I'm sure he is not the only one. Let's discuss that elsewhere. 

Separately, I am confirming that I am able to receive DMs into a new Coracle created npub from Damus with changing any DM settings.

**Comment by staab** [comment]
This is released to production
