### ISSUE TITLE
coinOS zaps dont show in primal, damus

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#105]
## client initiating action
?

## client receiving or observing action (or lack thereof)
primal, damus

## timestamp
https://njump.me/nevent1qqsq5eafg03t6gr0zfrs3vjehxnh0x8ewy7ckvmu0ykxzjqunan8eucpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgswaehxw309ahx7um5wgh8w6twv5q3samnwvaz7tmjv4kxz7fwdehhxenvv9ex2tnrdaksz9rhwden5te0wfjkccte9ejxzmt4wvhxjmcq2at6d

## what happens 
coinOS zap receipts/notifications dont show in primal, damus

### futher context

damus may have missing zap notifications currently (1.10.1)  https://github.com/damus-io/damus/issues/2543

**Comment by alltheseas** [comment]
@asoltys

**Comment by SamSamskies** [comment]
Doesn't seem like Coinos zap receipts are being published right now

**Comment by asoltys** [comment]
Fixed https://github.com/coinos/coinos-server/commit/9ef8f0eea743929207009d0f42b9ba44eec00641
