### ISSUE TITLE
albyhub x damus NWC issue

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#114]
## client initiating action
damus

## client receiving or observing action (or lack thereof)
damus

## timestamp

https://njump.me/nevent1qqsymkv2gj3r7qvjv8qgyx9ky84gsf0hfxdsksqkxuwn6g9p4vvdu9sppamhxue69uhkumewwd68ytnrwgq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7qgswaehxw309ahx7um5wgh8w6twv5q3gamnwvaz7tmjv4kxz7fwdehhxarj9e3xwk6se0u

**Comment by alltheseas** [comment]
@bumi @jb55

**Comment by bumi** [comment]
It works for me. I don't really understand the issue to be honest.

**Comment by alltheseas** [comment]
I did not hear back from the customer
