### ISSUE TITLE
Damus Primal Profile Edit Issue

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#12]
## client initiating action
Damus

## client receiving or observing action (or lack thereof)
Primal

## timestamp
https://njump.me/https://damus.io/nevent1qqstu4ea3t4l83dv8666n6nyd3fafftxsmnjxx6uy7t63g8gvhhe36sprpmhxue69uhhyetvv9ujuumwdae8gtnnda3kjctvqy2hwumn8ghj7mn0wd68ytnfdehhxarp9e3kxqg5waehxw309aex2mrp0yhxgctdw4eju6t0qy8hwumn8ghj7mn0wd68ytnddaksz9nhwden5te0v96xcctn9ehx7um5wghxcctwvsq3gamnwvaz7tmjv4kxz7fwdehhxarj9e3xwqgawaehxw309ahx7um5wgkhqatz9emk2mrvdaexgetj9ehx2aqpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqg5waehxw309ahx7um5wghx77r5wghxgetkqyv8wumn8ghj7un9d3shjtnwdaehw6r9wfjjucm0d5q3samnwvaz7tmjv4kxz7fwdehhxarjv96xjtnrdaksz9thwden5te0dehhxarj9ekkjmr0w5hxcmmvqyw8wumn8ghj7mn0wd68ytnzd96xxmmfdejhytnnda3kjctvqyvhwumn8ghj7ur4wfshv6tyvyhxummnw3ezumrpdejqzxnhwden5te0wfjkccte9ehhyctwvajhq6tvdshxgetkqyxhwumn8ghj7mn0wvhxcmmvqy2hwumn8ghj7etyv4hzumn0wd68ytnvv9hxgqgcwaehxw309aex2mrp0yhxummnw3ezucm0d5hxzagpzpmhxue69uhkummnw3ezuamfdejssjlag4

## what happens 
Profile changes made in Damus not saved.

Profile changes made in Primal iOS not reflected in Damus. 

## suggestion

**Comment by jb55** [comment]
>Profile changes made in Damus not saved.
>
>Profile changes in Primal not reflected in Damus.

I experienced the damus not updating today, but it was just a UI thing.
need to investigate further.

This is probably just a damus bug, not an interop thing

**Comment by shawnyeager** [comment]
Yes. I offered up Primal just a confirmation that another client would work as expected.
