### ISSUE TITLE
reply from Iris messenger appears as stand-alone note

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#121]
## client initiating action

Iris

## client receiving or observing action (or lack thereof)

Damus, Amethyst

## timestamp

https://njump.me/nevent1qqsd7qcs3sp00jmgyumknl83zjj44vdzctss89w2juy4rnt8gsayjmq9l9c39

https://njump.me/note1yu3kvc3xmd6k4me5rug00245fc6626s7fu44z6u3lhrewcymm2sskvw2v7

## what happens 
reply from Iris messenger appears as stand-alone note

reply event only has "p" tags per @hzrd149

**Comment by alltheseas** [comment]
@mmalmi @vitorpamplona @callebtc

**Comment by mmalmi** [comment]
Should be fixed now
