### ISSUE TITLE
Primal/Strike cannot zap Alby and vice versa

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#24]
## client initiating action
Primal (wallet)

## client receiving or observing action (or lack thereof)

unknown

## timestamp

https://njump.me/nevent1qqsgymw25taf79u4tc3nlxpcq66avqsnyy95jx4ngrrxz5guwnfxfycaflze0

## what happens 

> couldnt zap some getalby addresses from Primal, while using Primal. And inversely, couldn’t zap primal addresses from getalby, while using Damus. Probably not a new issue. But noticed last week when I tested Primal

**Comment by alltheseas** [comment]
@mbrat1 @kiwiidb @bumi

**Comment by alltheseas** [comment]
https://njump.me/nevent1qqs00p8lugves0g47846a26rukhvrv2jwkyc9p63a4yhlfyt72vlpdspzpmhxue69uhkummnw3ezuamfdejszuthwden5te0ve5kcar9wghxummnw3ezuamfdejj7mnsw43rzun6vuunv7n2v9mxwct5wdur2cmgxfm8var3x3shgct5d3un2unkv3mhzem2wqc82arcwu6r27n90fh8v7t3vejxk7rkv5lkyun0v9jxxctnws7hgun4v5nxwmr0vfskc0tpd3kqzyrhwden5te0dehhxarj9ekxzmnyqyw8wumn8ghj7mn0wd68ytndw46xjmnewaskcmr9wshxxmmdtrw3we

npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve using primal
Attempting to zap

npub19xgymswuxyq4sx58enft9c6algrm72a6lchplm4rjzgklufn9ygq5kcu58

frogfren17@getalby.com

And

npub12rzunrxvx89f78h4df284lzvkjqetljkq0200p62ygwmjevx0j8qhehrv9

rexdamascus@getalby.com

Note references in top of thread (I have issued with missing notes in Damus).

**Comment by alltheseas** [comment]
For Alby + amethyst

npub19xgymswuxyq4sx58enft9c6algrm72a6lchplm4rjzgklufn9ygq5kcu58

frogfren17@getalby.com

Cannot zap npub1rzg96zjavgatsx5ch2vvtq4atatly5rvdwqgjp0utxw45zeznvyqfdkxve

issanode@getalby.com

Https://njump.me/note1evwmavs8s4wrufrq5hntsld44wghfems3l3nk83hea2c7jdzsrmslvfvkf

**Comment by alltheseas** [comment]
One more cannot zap from alby to primal

https://njump.me/nevent1qqs8etlm7j0rzkr2v569ads3h6yt0d53hz7lr8qlhtyfkjuw3zg0ucgjvrece

Alby npub1jk9h2jsa8hjmtm9qlcca942473gnyhuynz5rmgve0dlu6hpeazxqc3lqz7

sersleepy@getalby.com

Primal npub1cd6syy4q0rha3kzdz2yw5782y4yj9snvzd8rcxjy6e9kldcmpeuq6dw96r

Justin_Tokyo@primal.net

**Comment by alltheseas** [comment]
@jimmymow is that alby cant zap strike?

**Comment by mbrat1** [comment]
The reason why sersleepy can't zap justin_tokyo is because justin never configured that custom lightning address with Primal. I just responded here: 

https://primal.net/e/note1scuwsqgq30ftf7xs9t83l3kezj6d8uq5207j7e6ck553vtu8jdpscfhsxv

Also confirming that Alby-Primal zaps work well in both directions.

**Comment by alltheseas** [comment]
@mbrat1 how about this one - same issue?

> sender npub1k3v47sfwz8ph99nuwufa249egw7wrwqfgkhyu0n4y0q9zkhcxpaqaj3dmq
zhenya@getalby.com

> receiver

> npub14q8uffuxxnhzd24u4j23kn8a0dt2ux96h5eutt7u76lddhyqa0gs97ct2x

😆> The receiver's lightning service at https://primal.net/.well-known/lnurlp/uno is not available. It was calculated from the lightning address "uno@primal.net". Error: 403

https://njump.me/note1s5gd7kcnvnhrjy6q3cvu7705vdkgd7cempg28urtfanxmy0dzl8qjczvzt

**Comment by mbrat1** [comment]
https://primal.net/.well-known/lnurlp/uno is resolving fine for me.

**Comment by alltheseas** [comment]
> https://primal.net/.well-known/lnurlp/uno is resolving fine for me. 

I asked the bug submitter to test again

In the meanwhile this issue now has an official meme

![image](https://github.com/nostrability/nostrability/assets/64376233/c3184a38-707c-4799-b0c4-4e8e35721042)

**Comment by alltheseas** [comment]
@mbrat1 issue reportedly persists. How can we troubleshoot next

https://njump.me/nevent1qqsfhhz7xtvdlxytpj94stk3xpls6cs232l7kd7lrpwqc5y5gztd47cpz3mhxue69uhhyetvv9ujuerpd46hxtnfduq3jamnwvaz7tms09exzmtfvshxv6tpw34xze3wvdhk6qg6waehxw309a3kzcmgv5cjuurjd9kkzmpwdejhgtmkxyq3jamnwvaz7tmjv4kxz7fwwdhx7un59eek7cmfv9kz7zqjatd

**Comment by alltheseas** [comment]
https://njump.me/nevent1qqspqvwes53cpcfu7gns0uu7w0eckxrhh7056l66tn8qe0g8quv7ugspr3mhxue69uhkummnw3ezumt4w35ku7thv9kxcet59e3k7mgpz4mhxue69uhk2er9dchxummnw3ezumrpdejqz9thwden5te0dp5hxapwdehhxarj9ekxzmnyqyvhwumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdshs38qeg2

**Comment by mbrat1** [comment]
Thanks for bringing this up @alltheseas! 

The issue seems to be specific to our Android client; zaps to Alby users work fine from Primal iOS. We are looking into it and aiming to publish a patch soon.

**Comment by alltheseas** [comment]
Tony advised resolved

https://njump.me/note1yjk3r0kz4e0uws6lfue4u9vm20ruqsfpfpps5wv24rcga3vvf55q2tv8fz

**Comment by alltheseas** [comment]
@TonyGiorgio @mbrat1 @jackmallers any learnings worth documenting here for other LN wallet devs?
