### ISSUE TITLE
Amethyst replies appear as quote notes in Damus

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#27]
## client initiating action

Amethyst quote to Damus created note

## client receiving or observing action (or lack thereof)

Damus observes a reply with a quote note (instead of only a quote note)

## timestamp

OP

https://njump.me/note1jdczpfek76zm9pz64uuwgvyx9upt2ncekx84hrtq3rv5m0473s4s0mj0cr

Reply with quote note on Damus

https://njump.me/ note180qwk6rh2czrjw2wr8uje8cxfkj4m6eupew9z3snzg7t3lfzkfls37m7eg

Quote note from Amethyst appears as reply with QN in Damus

![image](https://github.com/nostrability/nostrability/assets/64376233/cdd49bd6-4325-4aed-9e2e-54801aff4995)

## what happens 

![image](https://github.com/nostrability/nostrability/assets/64376233/b2041237-14ce-4330-ad71-cad5693b81ed) quote note from Amethyst appears as reply with quote note in Damus

## suggestion

@vitorpamplona advises 

> No idea why this is not being rendered. The post has the Q tag and the mention tag to be backwards compatible. So, in theory every Client should be able to render this properly.

**Comment by alltheseas** [comment]
@jb55

**Comment by vitorpamplona** [comment]
This is a Quote from Amethyst, not a reply.

**Comment by alltheseas** [comment]
> This is a Quote from Amethyst, not a reply.  It should be rendered as a quote on both `q`-tag clients and `mention`-marker clients. 

Thanks for the clarification - I had not verified on Amethyst. I updated the issue. 

I will add an Amethyst screenshot later today.

**Comment by vitorpamplona** [comment]
Here's how the post is displayed on Amethyst. 

![Screenshot_20240325_180033](https://github.com/nostrability/nostrability/assets/532031/37c8e8da-f394-4408-a269-403059cfd942)

**Comment by vitorpamplona** [comment]
I did a quick check with Nostur, which also uses the q-tag, and it seems to be rendering as a new post like the other `mention` clients are doing. 

![Image 3-25-24 at 6 13 PM](https://github.com/nostrability/nostrability/assets/532031/37ee679d-a983-429a-861e-b1c2765fd70a)

**Comment by alltheseas** [comment]
On Damus 1.8, 1.9 this issue is resolved

**Comment by alltheseas** [comment]
1.9 mobile ![image](https://github.com/nostrability/nostrability/assets/64376233/39a43b3b-0e38-4096-89c1-d9c5ea9070d2)

**Comment by alltheseas** [comment]
1.8 (2) 

<img width="527" alt="Screenshot 2024-05-20 at 12 19 23 PM" src="https://github.com/nostrability/nostrability/assets/64376233/19ccf82f-5e22-4439-93d7-3cf650812373">
