### ISSUE TITLE
Zapping from alby to mutiny shows double

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#30]
## client initiating action
Alby via Amethyst

## client receiving or observing action (or lack thereof)
Sending to mutiny

## timestamp

https://njump.me/nevent1qqspv8pvsp5j9mmlpjwxcals42cc2j8w2g4fe0dnu6em8hq5u38350qpr9mhxue69uhhq7tjv9kkjepwve5kzar2v9nzucm0d5q3vamnwvaz7tmndpshwm3wdehhxarjxyhxxmmdqyxhwumn8ghj7mn0wvhxcmmvqyg8wumn8ghj7mn0wd68ytnhd9hx292cch2

![image](https://github.com/nostrability/nostrability/assets/64376233/76b2b92a-e746-43a2-9de7-a512b7e3cafe)

## what happens 

A single zap shows as double

## suggestion

@kiwiidb @benthecarman

**Comment by benthecarman** [comment]
I know the cause of this, thanks for the report

**Comment by alltheseas** [comment]
Thanks - I think you should be able to close this issue when you push the fix. 

cc @utxo-one
