### ISSUE TITLE
Zbd breaks damus contacts, relays

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#32]
## client initiating action

Zbd

## client receiving or observing action (or lack thereof)

Damus

## timestamp

https://njump.me/nevent1qqszsdxqueud7dg8f28fwn5e2g4vfx8704l2mfm7ykvqpqlmzr923qcprpmhxue69uhhyetvv9ujumn0wd68ytnrdakjuct4qyg8wumn8ghj7mn0wd68ytnhd9hx2qg6waehxw309aex2mrp0yhx7unpdenk2urfd3kzuer9wcq3vamnwvaz7tmpw3kxzuewdehhxarj9ekxzmnyr42750

## what happens 

> Esiste un modo per tenere sincronizzati i contatti e i relay tra #ZBD e #damus? Perché tutte le volte che entro nella sezione social di #ZBD poi in #damus succede un casino, mi spariscono parecchi contatti e alcuni relay.
Oppure #ZBD e #damus non vanno d’accordo

> Is there a way to keep contacts and relays synchronized between #ZBD and #damus? Because every time I enter the social section of #ZBD then a mess happens in #damus, several contacts and some relays disappear.
Or #ZBD and #damus don't go together

## suggestion

@fiatjaf pls fix your client

**Comment by alltheseas** [comment]
@zantoshi

**Comment by fiatjaf** [comment]
ZBD Social profiles are really not meant to be used from the external world.

**Comment by alltheseas** [comment]
Imagine being the first social gaming company to adopt an open standard identity system, and make sure it works. I think this will bring in dividends for y'all.

Irregardless of what I think will you tell your customer, or do you want me to?

**Comment by jb55** [comment]
why not build something proprietary if you don't want leakage to a wider open protocol?

**Comment by fiatjaf** [comment]
I want leakage and interaction of ZBD users with the rest of Nostr, it's just that the custodial backend, for various reasons, is not made for users that control their keys from the outside, they're meant to be custodial users forever (or they can export their key, but then they stop existing internally).

Unfortunately there was an "import key" feature in the past that caused the situation here described. That feature has been disabled now so it shouldn't happen again.

My recommendation is that the user uses Damus only for browsing and posting, but do contact list changes only inside ZBD -- or go on ZBD and click to export key so they exit fully and their keys get deleted from ZBD.

Or use https://follows.nostr.com/ to fix their contact list every once in a while.
