### ISSUE TITLE
Damus and nostrudel show different relay lists

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#35]
## client initiating action

Damus

## client receiving or observing action (or lack thereof)

Nostrudel

## timestamp

https://njump.me/nevent1qqsfqsqsnqpt86d686draaaqyhqzjkegnr2yxf0uspu3t3vrxsyw6wqp84mhxw309a3xjarrda5kuu3kv3jn2mrtweurgarswajx67njv3nxgurvvy6hx7tpxfskvamsvdsky6n4wqe8surfx4j82mrzv9jqzsmhwvaz7tmwdaehgunvv9hxgvn8v3mnween0ymnwcm5ve6x7ankd9krwdnkw96kjured4hnwarnvd6xc7rsd9mkkmn9weaxv6ty9ehku6t0dcq5xamn8ghj7vn2wdhxc6rxdejkc6t8x4skxufkd9skx7tyd4axgcnyd4nnw7rhw4hx6drcdsm8zamzweaxzcmhx3k8wun2d4k8jepwdahxjmmwq9phwue69uhk77r5wfjx2anpwcmrg73kx3ukydmcxeex5ee5de685ut2dpjkgmf4vg6h56n3w4k82emtde585u35xeh8jvn3vfskgtn0de5k7msxl0tpc

## what happens 

Damus shows one relay list, while nostrudel shows another for same user/npub. 

## suggestion

@hzrd149 @jb55

**Comment by jb55** [comment]
this is a damus issue

**Comment by hzrd149** [comment]
noStrudel runs off of two sets of relays, your mailboxes (NIP-65) and the app relays (local relays)
The screenshot in question is showing the app relays which are stored locally on the device and not synced with other apps.

Having the app relays separate allows you to add and remove relays without effecting your NIP-65 outboxes or inboxes

**Comment by alltheseas** [comment]
> this is a damus issue

https://github.com/damus-io/damus/issues/2186#issuecomment-2078352636
