### ISSUE TITLE
Muting vs Muting 

### ISSUE THREAD

**Issue by realjode** [nostrability/nostrability#36]
Regarding the #nostr  muting business:

It would be great if when we mute someone it would be like a Sparta kick into the blackness of space with the user never seeing the muted again. 

At the moment, if I mute a user I will still their notes if a followed user ‘quotes’ one of the muted users notes. 

Would it be possible to implement a protocol wide real Sparta mute ? 

I think this may help those that want to move on from someone or something they just don’t ever want too see. 

💜🫂

**Comment by jb55** [comment]
this is really just a client implementation detail, sounds like you're describing how damus does it. we can add a sparta mute as an option.

**Comment by realjode** [comment]
That would be great 🤙🏽

**Comment by alltheseas** [comment]
Closing this as it sounds addressable from each app.
