### ISSUE TITLE
mute list is wiped 

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#44]
## client initiating action

nostrudel, or amethyst, or ZapStream

## client receiving or observing action (or lack thereof)

nostrudel, or amethyst, or ZapStream

## timestamp

https://njump.me/nevent1qqsyuunf3ly3qr4yjxslr34l72r0lmdc2z84ly8v34xdhhjtcr9etugpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgdwaehxw309ahx7uewd3hkcqg6waehxw309aehgatyd9hnxvf59ehx7um5wgcjucm0d5q3wamnwvaz7tmjv4kxz7fwwpkx2cnnw3ezucm0d57g9eqa

> really only use noStrudel, Amethyst and ZapStream and never had an issue like this. The same muted accounts continue to reappear for me for like the last 1-2 weeks. Very odd.

## what happens 

mute list is wiped

**Comment by alltheseas** [comment]
@vitorpamplona @hzrd149 @v0l have yall heard reports about mute list wipes with your apps?

**Comment by vitorpamplona** [comment]
Yep, some clients delete the private (encrypted) `.content` part of lists. Amethyst saves to the private part only. So, if the `.content` gets deleted it brings everyone back.

**Comment by vitorpamplona** [comment]
It could also be that some clients are already encrypting in NIP44 and others are not. NIP-04 has been deprecated for a long time now. Most of the new clients only do NIP-44

**Comment by bu5hm4nn** [comment]
So are you saying some clients just use a different encryption standard without any hint in the data? Like a prefix or a new tag? Maybe it should be `.content-44` or something like that.

**Comment by vitorpamplona** [comment]
> So are you saying some clients just use a different encryption standard without any hint in the data? Like a prefix or a new tag? Maybe it should be `.content-44` or something like that.

If there is something I learned on Nostr is that there is always some rogue client doing something weird, either intentionally or not. I have heard about kind:4 messages encrypted with NIP-44, but I don't have one to provide as an example. :(

**Comment by alltheseas** [comment]
Zapstream is fixed - closing until I hear otherwise
