### ISSUE TITLE
Damus kind 7 reacts to the wrong event

### ISSUE THREAD

**Issue by alexgleason** [nostrability/nostrability#48]
## client initiating action

Damus?

## client receiving or observing action (or lack thereof)

Ditto

## timestamp

```jsonl
{"kind":7,"id":"5b80bcb6b5dd602ba19406f39dfb3b296c5ab2d4d699444fd234476f2b774473","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717618964,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","wss://relay.primal.net","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","676c173c72994eb7fad07086c3bbbb2dfee00f788ccf69c27979fc35999fe9e5"],["p","3f770d65d3a764a9c5cb503ae123e62ec7598ad035d836e2a810f3877a745b24"]],"content":"🫂","sig":"bbd34589bdc1875d71d591b29c7388fafa2cb884c06ad651af21457aeca2d6fd7aca8f54cffff7fec81b838d1b1a5c515ba57ea0a8116ea6ea76325292bdc639"}
{"kind":7,"id":"fbee16aea2fc9bfa42960d0d8670bef45abb9c1c5acfba927ebcab628b4985d7","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717618554,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","0b88881e42632233b7e7d647d1ada41f5614ae79fa4556089c9656e99a653593"],["p","f07e0b1af066b4838386360a1a2cbb374429a9fbaab593027f3fcd3bd3b5c367"]],"content":"🫂","sig":"8b2d075f4ebe80bd3b095c4df83c8b8a93b50e117c3a5af43e7fcba50bc0f768d652a4684b8d24b996d237de284f285c46994190a9e11e693002304d5ed3e48d"}
{"kind":7,"id":"3c364a7efd3dd3e80d3171f296acc87a40e2ae8bad781d9869dd20fb70eb448b","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717617032,"tags":[["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","499ed4f696e5a773fb5cd05fc40d5a763b5b665d57cfabaca57ebd26e77c76dd"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"]],"content":"🫂","sig":"f4144f9cf2e0da27febd3b579fab6fa905ace3f9531e9fa3bda4e7e0277bf462a6760da03cb1e2dedbafc35bd99e1879fde5794d6d60af5881f6f0d3f5070318"}
{"kind":7,"id":"88295f07e174410a99ddae244944de0b65efd168b58e7a9ed4eae5f1d3c9e8aa","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616984,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","9b212a388cd91d4a18483f262c8f941acc9e026b0ed40216926c58b253941958"],["p","520830c334a3f79f88cac934580d26f91a7832c6b21fb9625690ea2ed81b5626"]],"content":"🫂","sig":"045f5037d82ddd8fa6830ec240ad7e6b05f6e3fec1a65576290cd30b55bf0c617256ec9fdc8bfe6c936cb90682cf5adc3e1bc5a974cfdf9b9e3648ac8fdc4ed1"}
{"kind":7,"id":"1e81407a0fc1a3cdb162b94505a6b16f6d8c767f5c322b5f6a0e80b60668f18c","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616981,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","wss://nostr.wine/","root"],["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","wss://nostr.wine/","reply"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","","mention"],["e","d1eeb5e8af00d205f6e7e9cced5df17cac96060e3543f68282c0339ad55ec857"],["p","acc925afdc7964b230915b48fd0b785ab2c85a94502a4ce8b17c7b80db9fb0bb"]],"content":"🫂","sig":"7a62ec1afe332554922db0811e840cd6fba58a06a7d312b8ea1cca3f05a899a5da1d4df6d8cdae67cc4ccfff2ebcdbe1d9a5cbdb3072d705bd1a9ab27519b98d"}
{"kind":7,"id":"e57169ebd035403eea40729b5f4399d92188fcd359d5c2131db8875c01a4ae00","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616978,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","root"],["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","reply"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["e","069299be1936e7c0fc234b1b872c3d153562eff1799237b6ce7870849bcd6be7"],["p","0461fcbecc4c3374439932d6b8f11269ccdb7cc973ad7a50ae362db135a474dd"]],"content":"🫂","sig":"90f6ba4121d8bcf55a792e78f7ce79a0621815e0873ccca1bfdd296be7c350bf8f3c5b84d07831bed1a67943ebf2e62efa1c78b13276bed6642b46e9d2f30a71"}
{"kind":7,"id":"1d166f7f1c23471b005b398296452db92be10b8e8cef1dd052ddc587295bf7e5","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616974,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","55ce50c23914d7f178880b1607df84bc1e381615854254beb9412f12fb37ddcd"],["p","1577e4599dd10c863498fe3c20bd82aafaf829a595ce83c5cf8ac3463531b09b"]],"content":"🫂","sig":"0610939053c1c3f78b7ee13213d2f224c535968e8cadcd6c90cd6b24de285977003c8fe08f17cac6d9738ff7a93c11f5886d88246f1e9d3fd873d716ad7f8592"}
{"kind":7,"id":"b1d81ab75b3833a4ef9d223137b52e1dba3d21897a6a580f7935e2026009ecd6","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616970,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","c4dc0b957b36e1177ae4177c256d096ba0e4c55b4fa58fb17b90a1116ed78c4a"],["p","4eb88310d6b4ed95c6d66a395b3d3cf559b85faec8f7691dafd405a92e055d6d"]],"content":"🫂","sig":"270da5c4208f56311a51a415d7fafbb9244b7ae778e0c16f030babdd312e97441348e3d91b0276b009bd3d9994f450c4e8ebdb16311de7704b81e03e5e8aaac3"}
{"kind":7,"id":"7b8f4990bf0bb4d52d496391cfb04c8727b782cc586d6cecdcd35a2c016ea483","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616968,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","5ee5c528dc8480bf9db3c29504350db33fb3bd60e37344c0717ca55a0b297821"],["p","50d46fb0720d18f0c0ded24662cfbc279a44c9a668d0ea01688dfdfb3c4a47ad"]],"content":"🫂","sig":"6bbe4d79b5864f6c439f137305cffb224b530c50b346f7691a0c555db4936ecee4f37c9db4e47a152008e3934135493bce535f01061bd52e488b5a2e271414f6"}
{"kind":7,"id":"f3d0b390364d352d13e7104d4c6110d33e759aedecf7000be4f8944c49a8aeef","pubkey":"2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1","created_at":1717616965,"tags":[["e","14c361f6323986f08c620ce99e1a9cb5d2c8b0ac0dd15d79ad6c0c19698e849e","","root"],["p","8083df6081d91b42bcf1042215e4bfc894af893cd07ea472e801bc0794da3934"],["p","58c741aa630c2da35a56a77c1d05381908bd10504fdd2d8b43f725efa6d23196"],["p","32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245"],["p","07ecf9838136fe430fac43fa0860dbc62a0aac0729c5a33df1192ce75e330c9f"],["p","2f4fa408d85b962d1fe717daae148a4c98424ab2e10c7dd11927e101ed3257b2"],["p","2779f3d9f42c7dee17f0e6bcdcf89a8f9d592d19e3b1bbd27ef1cffd1a7f98d1"],["e","0cdfb961e26af7d644b43a7fd97112e3eac77a8043c86cd1b1addceb89295093"],["p","d60397e8a390b41dd17551b04be27ad26831beb6d55a98a1f14d94ec2fe3fde0"]],"content":"🫂","sig":"aee40427fc30cae6c8e36c9638e8ba55096104a7503b8d340fa2b8e254170880bae5801f8dbc7628204679518ce82f8aefb31b068714c60a6b24c112ac2e9ff0"}
```

## what happens 

Whichever client @tyiu is using (Damus?) is copying tags from the whole thread in the kind 7 event, so it includes multiple "p" and "e" tags. This makes it appear he is reacting to his own event instead of to my comment.

![Screenshot from 2024-06-05 15-40-44](https://github.com/nostrability/nostrability/assets/3639540/08bf4d72-acb9-4906-a660-b4070bdca097)

cc @jb55 

## suggestion

Include only one "e" tag and "p" tag in the event.

**Comment by tyiu** [comment]
Yeah, it's Damus.

**Comment by tyiu** [comment]
I'll fix it. It shouldn't be hard.

**Comment by alltheseas** [comment]
thank yall

@tyiu see https://github.com/damus-io/damus/issues/2150

**Comment by tyiu** [comment]
Actually, I don't know if including only one `p` tag is right. What if the note that I'm reacting to mentions some `p` tags. Maybe those mentioned pubkeys would want to be able to query reactions for notes that they're mentioned in.

**Comment by tyiu** [comment]
Would they need to make two queries? Query for all notes that they've been mentioned in, and then query for reactions on those notes? Not sure which way is more acceptable.

**Comment by tyiu** [comment]
If we don't carry over all the `p` tags, then it makes it much harder for a client to provide notifications to those who were mentioned and weren't the authors. So I feel like carrying over `p` tags might be better. What do you think, @alexgleason?

**Comment by alexgleason** [comment]
> Actually, I don't know if including only one `p` tag is right. What if the note that I'm reacting to mentions some `p` tags. Maybe those mentioned pubkeys would want to be able to query reactions for notes that they're mentioned in.

I got notified of an event I was quoted in, and I didn't mind that.

![image](https://github.com/nostrability/nostrability/assets/3639540/63f448dc-6354-4cb1-957f-d98f9cdfa11c)

But the spec says just 1 e and 1 p tag.

**Comment by tyiu** [comment]
OK, I'll see what Will says with the PR with just the one `p` and one `e` tag.

**Comment by jb55** [comment]
On Wed, Jun 05, 2024 at 07:37:19PM GMT, Terry Yiu wrote:
>OK, I'll see what Will says with the PR with just the one `p` and one `e` tag.

shouldn't they have two 'e' tags on reactions to thread replies, so you
can pull all likes in a thread like we do with kind1 notes?

also one `p` tag is restrictive, as it doesn't allow us to show things
like "bob liked a post you were mentioned it"

**Comment by jb55** [comment]
On Wed, Jun 05, 2024 at 07:34:05PM GMT, Alex Gleason wrote:
>> Actually, I don't know if including only one `p` tag is right. What if the note that I'm reacting to mentions some `p` tags. Maybe those mentioned pubkeys would want to be able to query reactions for notes that they're mentioned in.
>
>I got notified of an event I was quoted in, and I didn't mind that.
>
>![image](https://github.com/nostrability/nostrability/assets/3639540/63f448dc-6354-4cb1-957f-d98f9cdfa11c)
>
>But the spec says just 1 e and 1 p tag.

This is not true, the spec says the *last* etag/ptag:

- The reaction event SHOULD include `e` and `p` tags from the note the user is
reacting to. This allows users to be notified of reactions to posts they were
mentioned in. Including the `e` tags enables clients to pull all the reactions
associated with individual posts or all the posts in a thread.

- The last `e` tag MUST be the `id` of the note that is being reacted to. 

- The last `p` tag MUST be the `pubkey` of the event being reacted to.
tag is the note you are liking.

**Comment by tyiu** [comment]
> On Wed, Jun 05, 2024 at 07:37:19PM GMT, Terry Yiu wrote:
> >OK, I'll see what Will says with the PR with just the one `p` and one `e` tag.
> 
> shouldn't they have two 'e' tags on reactions to thread replies, so you
> can pull all likes in a thread like we do with kind1 notes?
> 
> also one `p` tag is restrictive, as it doesn't allow us to show things
> like "bob liked a post you were mentioned it"
> 

It seems like NIP-25 could be updated so that clients are smart enough to understand tag markers (root, mention), just like what kind 1 events do.

**Comment by tyiu** [comment]
> On Wed, Jun 05, 2024 at 07:34:05PM GMT, Alex Gleason wrote:
> >> Actually, I don't know if including only one `p` tag is right. What if the note that I'm reacting to mentions some `p` tags. Maybe those mentioned pubkeys would want to be able to query reactions for notes that they're mentioned in.
> >
> >I got notified of an event I was quoted in, and I didn't mind that.
> >
> >![image](https://github.com/nostrability/nostrability/assets/3639540/63f448dc-6354-4cb1-957f-d98f9cdfa11c)
> >
> >But the spec says just 1 e and 1 p tag.
> 
> This is not true, the spec says the *last* etag/ptag:
> 
> - The reaction event SHOULD include `e` and `p` tags from the note the user is
> reacting to. This allows users to be notified of reactions to posts they were
> mentioned in. Including the `e` tags enables clients to pull all the reactions
> associated with individual posts or all the posts in a thread.
> 
> - The last `e` tag MUST be the `id` of the note that is being reacted to. 
> 
> - The last `p` tag MUST be the `pubkey` of the event being reacted to.
> tag is the note you are liking.
> 

I actually recall the spec looking like what you said at one point, but it must have changed since because it doesn't say that anymore.
https://github.com/nostr-protocol/nips/blob/master/25.md

**Comment by jb55** [comment]
oh right, I forgot nostr is just whatever Vitor says without asking the original NIP author why I did that. Another reason why the nips repo is a joke at this point.

**Comment by jb55** [comment]
I really don't see how nostr survives when people do this. I'm so fucking done with this shit.

**Comment by fiatjaf** [comment]
This was bad indeed. I'll revert it in the NIPs repo.

**Comment by alltheseas** [comment]
> This was bad indeed. I'll revert it in the NIPs repo.

Whats the protocol/process for NIP changes? Is it anyone with permission can change? M/n quorum? Veto?

**Comment by alexgleason** [comment]
Are you saying I should be able to use findLast instead of find on the tags to fix my implementation? Or should I be looking for markers on the tags?

**Comment by jb55** [comment]
On Thu, Jun 06, 2024 at 08:44:34AM GMT, Alex Gleason wrote:
>Are you saying I should be able to use findLast instead of find on the tags to fix my implementation? Or should I be looking for markers on the tags?

nip10 markers are only needed for constructing replies, so if you're
replying to likes then sure you can look at those. We do the last tag
thing because it is compatible with the deprecated form of nip10 if you
ever wanted reaction replies.

The main point is just to have the root etag available so the likes get
picked up in the thread query.

you don't need to look at markers when constructing replies, you just
use the last tag.

It's possible I broke something wrt. constructing reactions when I added
nip10 markers to damus, as I have definitely seen reactions getting
picked up on wrong events, but i haven't dug into it too deeply yet.

**Comment by alexgleason** [comment]
Cool, that fixed it. Thanks!

https://gitlab.com/soapbox-pub/ditto/-/merge_requests/362/diffs

![image](https://github.com/nostrability/nostrability/assets/3639540/c43ed940-8d52-41c6-af8a-a6723211f1e5)
