### ISSUE TITLE
Zaps received to coinOS do not show in damus, primall

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#58]
## client initiating action

Placeholder

## client receiving or observing action (or lack thereof)
Damus: no zap seen
Primal: no zap seen

## timestamp

https://njump.me/nevent1qqswepmnz3rfkwf8xhdcee93h4jylqsa97y8ue38mk2jhkke6jseqdcprpmhxue69uhhyetvv9ujuumwdae8gtnnda3kjctvqyg8wumn8ghj7mn0wd68ytnhd9hx2qgdwaehxw309ahx7uewd3hkcqgkwaehxw309aex2mrp0yhxummnw3ezucnpdejq96cj7u

## suggestion

**Comment by alltheseas** [comment]
CoinOs context https://github.com/coinos/coinos-server/issues/62

**Comment by SamSamskies** [comment]
the issue is with coinos' lnurl server https://github.com/coinos/coinos-server/issues/63. i just made a PR to fix it https://github.com/coinos/coinos-server/pull/64.

**Comment by SamSamskies** [comment]
@alltheseas you can close this. Zaps are finally working with coinos lightning addresses!

https://github.com/coinos/coinos-server/pull/64

**Comment by alltheseas** [comment]
@SamSamskies lmk if more attention needed

**Comment by alltheseas** [comment]
Thank you @asoltys
