### ISSUE TITLE
onboarding confusion: name, username, nostr address, npub

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#81]
Benefit: reduce confusion for nostr newbies

via @dtonon 

> We should stop pairing NIP-5 with the word "verification". For newcomers it risks being a shitcoin game.
Use NIP-5 for its real functions and embrace WoT for actual contacts check.

https://njump.me/nevent1qqsrpvvhnu5fu8gaudnlnuk7cdp3m5yezl6w88x9t38c3zdhaju52tcpzemhxue69uhhyetvv9ujuurjd9kkzmpwdejhgqguwaehxw309ahx7um5wghxy6t5vdhkjmn9wgh8xmmrd9skcqghwaehxw309ahx7um5wghxvmt59emkj73wvf5h5qg5waehxw309ahx7um5wghrzumpwshx7un8ys9k4d

**Comment by jb55** [comment]
I think a bunch of us settled on "nostr address" instead of "nip05 verification" a long time ago.

**Comment by dtonon** [comment]
@alltheseas

> 
@dtonon where do you encounter 'verification' terminology?

Check the mentioned thread. It's quite common that users talk about "verification".
I'm not aware of any client that use it, maybe some NIP-05 services.

**Comment by dtonon** [comment]
@alltheseas 

> Renamed thread to onboarding confusion: name, username, nip-05, npub.

This is a really broad topic; I would only keep this topic for the incorrect terminology of “verification”, it can be useful as reference.

Btw, NIP-05 has been already updated with an additional note:
https://github.com/nostr-protocol/nips/commit/da34c57e99dbf6cadfb3b4176b7c4ff33ac5674c

**Comment by alltheseas** [comment]
> This is a really broad topic; I would only keep this topic for the incorrect terminology of “verification”, it can be useful as reference.

Sure.

In reviewing new people's observations joining nostr from past week, onboarding remains rough.
