### ISSUE TITLE
Damus does not support NIP-10 replies / not compatible with GitNestr (F/ka reply from Damus does not show up in Primal)

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#9]
## client initiating action
Damus

## client receiving or observing action (or lack thereof)
Primal

## timestamp
https://njump.me/note1us8pgca6zgvufxramm07cukte4vhw06eu0jst6hud5tjecn3ehvqryhd0p
1/26/24

## what happens 
Reply on Damus not seen in Primal.

Prospective explanation:

> It's a client issue. I've noticed some clients only fetch a few relays, typically the fastest ones, even if you have more than 20 configured. For instance, the #noStrudel client by default only checks the 4 fastest ones. Sometimes, your note may not be included in any of these selected relays and will result in it not being displayed in that specific case. I assume #Primal functions similarly. I tested on #Snort and your note appeared correctly, but on noStrudel didn't (unless I configured it to fetch all relay).

**Comment by alltheseas** [comment]
@moysa

> seems that his event is missing the `reply` and `root` in the `e` tag

**Comment by benthecarman** [comment]
https://github.com/PrimalHQ/primal-web-app/issues/53

**Comment by jb55** [comment]
looks like they don't suport the deprecated form of nip-10. I've had many issues with markers which is why I had yet to implemented, but I guess now some apps don't care about the deprecated form at all.

**Comment by fiatjaf** [comment]
I don't get why people don't implement both forms. It costs basically nothing.

**Comment by alltheseas** [comment]
> I don't get why people don't implement both forms. It costs basically nothing: look for markers -- if they exist use that, otherwise infer the role from the tag position.

If this is the correct solution, and this is not specified on reply/note/related NIP(s) whats the best place to store this best practice?

**Comment by fiatjaf** [comment]
I don't know. Maybe the NIP is the best place indeed. But we should ask other people if they see any problems with that solution.

**Comment by alltheseas** [comment]
> [Primal] introduced a regression in our backend when we changed the way rquoted notes are displayed in the feed. previously if you created a new note and quoted another note within it, we would list your note in the reply thread of the quoted note. dorsey pointed out that this was weird and we fixed it, but introduced this regression.

**Comment by alltheseas** [comment]
@tyiu 

> I spent about an hour looking through the Primal iOS code, and the code doesn’t match up with the reported behavior. The code adds a “reply” marker event tag before some “p” tags, but nowhere does it create a “root” marker event tag.

> createNostrReplyEvent code: https://github.com/PrimalHQ/primal-ios-app/blob/3b1f2d13f261348ecdc219bc600043509d1d926d/Primal/Common/Nostr/NostrObject%2BExtra.swift#L221-L226

> The current App Store version is 1.2.46 but what’s checked into GitHub is 1.2.30. The GitHub repository is 16 builds behind, so the backwards incompatible bug might have been introduced in one of those builds.

> App Store: https://apps.apple.com/us/app/primal/id1673134518

> GitHub repo version: https://github.com/PrimalHQ/primal-ios-app/blob/3b1f2d13f261348ecdc219bc600043509d1d926d/Primal.xcodeproj/project.pbxproj#L2443

**Comment by alltheseas** [comment]
https://njump.me/note1gynzl38jsv9v0kl27cchmazd8s8u96a307tu6p7cjyx3n5zpknpszvev3z

https://github.com/damus-io/damus/issues/2145

**Comment by alltheseas** [comment]
@tyiu advised submitted a fix to Primal to back Primal backwards compatible with Damus. Damus is still using deprecated version of nip-10. Primal team to advise when next iOS version is released.

https://njump.me/note177l7ura0gt0zmszw2gdngfhx94yfzsduup8mkdll5a422dlkjuaqw4d6z7

**Comment by mbrat1** [comment]
thanks for submitting the fix @tyiu; merged! planning a public update by the end of next week.

**Comment by alltheseas** [comment]
@mbrat1 can you kindly confirm if you have pushed the @tyiu  nip-10 update on primal so we can test?

**Comment by alltheseas** [comment]
@tyiu advised fixed

**Comment by alltheseas** [comment]
@ColbySerpa advised damus not compatible with GitNestr

https://njump.me/nevent1qqsg7n0slfzn4m6tsdx9spxgm5mka8gxwkjctln69gk6q3mfjqvlj3sprfmhxue69uhhg6r9vehhyetnwshxummnw3erztnrdaksz9nhwden5te0wfjkccte9ec8y6tdv9kzumn9wsq3vamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmnyqyfhwumn8ghj7un9d3shjctzd3jjummjvuag6s8j

**Comment by alltheseas** [comment]
@jb55 implemented marker support nip-10

**Comment by alltheseas** [comment]
@jb55 to advise on nip-10 test corpus for other apps #38
