### ISSUE TITLE
emoji sentiment analysis matrix

### ISSUE THREAD

**Issue by alltheseas** [nostrability/nostrability#91]
### what is this
In #88 there has been discussion on kind-1984, and reactions used to mark something as negative. A suggestion in #89 has been brought up for apps to consider not conflating reactions as 'likes' (i.e. carrying positive sentiment).

### sentiment analysis
The implication is that reactions can be classified as having positive, neutral, or negative states. Below is an attempt at mapping standard emoji characters to or between a positive (+1), neutral (0), or negative (-1) sentiment.

### call for experimentation
This is not a spec, nor advocacy for all nostr apps to adopt this classification. My hope is that one or a couple apps can try experimenting with sentiment analysis in part based on reactions, and they can share their learnings. This can surface positive feeds (anti-twitter), and negative feeds (twitter). The former might be used for 'consumption', whereas the latter could be  surfaced to the user as an opt-in method to eliminate certain types of notes.

### starting point: output from LLM

Creating a sentiment analysis matrix for emojis involves categorizing each emoji based on its perceived sentiment. Below is a simplified two-column matrix with emojis from both iOS and Android default keyboards, scored as +1 for positive, 0 for neutral, and -1 for negative sentiment.

### Emoji Sentiment Analysis Matrix

| Emoji | Sentiment Score |
|-------|------------------|
| 😀    | +1               |
| 😃    | +1               |
| 😄    | +1               |
| 😁    | +1               |
| 😆    | +1               |
| 😅    | +1               |
| 😂    | +1               |
| 🤣    | +1               |
| 😊    | +1               |
| 😇    | +1               |
| 🥰    | +1               |
| ❤️    | +1               |
| 💖    | +1               |
| 👍    | +1               |
| 👏    | +1               |
| 😍    | +1               |
| 😋    | +1               |
| 😎    | +1               |
| 😺    | +1               |
| 🎉    | +1               |
| 🌟    | +1               |
| 😐    | 0                |
| 😶    | 0                |
| 😏    | 0                |
| 😬    | 0                |
| 🤔    | 0                |
| 😳    | 0                |
| 😅    | 0                |
| 😒    | -1               |
| 😞    | -1               |
| 😔    | -1               |
| 😟    | -1               |
| 😢    | -1               |
| 😭    | -1               |
| 😤    | -1               |
| 😠    | -1               |
| 😡    | -1               |
| 🤬    | -1               |
| 💔    | -1               |
| 👎    | -1               |
| 😱    | -1               |
| 😨    | -1               |
| 😰    | -1               |
| 😩    | -1               |
| 😫    | -1               |
| 😵    | -1               |
| 🤯    | -1               |

### Notes:
- The sentiment of emojis can be subjective and may vary based on context and individual interpretation.
- This matrix includes a selection of commonly used emojis; there are many more emojis available on both iOS and Android keyboards.
- The neutral emojis are those that do not convey a strong positive or negative sentiment.

**Comment by alltheseas** [comment]
What do yall think @staab @vitorpamplona

**Comment by vitorpamplona** [comment]
Looks ok to me if people want to do this.

**Comment by staab** [comment]
If the purpose is to map emojis to +/- reactions, that's impossible because the same emoji can be used in different ways depending on context. If people want to show some kind of sentiment dial I guess that's fine, sort of interesting.

**Comment by vitorpamplona** [comment]
Just for reference, I think a better mapping/scoring should consider intensity as well. 

There are lots of good research out there, like: 

[![](https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-021-04357-7/MediaObjects/41598_2021_4357_Fig1_HTML.png)](https://www.nature.com/articles/s41598-021-04357-7/figures/1)

**Comment by alltheseas** [comment]
where is that from, looks great @vitorpamplona

**Comment by jb55** [comment]
I'm confused what this has to do with interoperability ?

**Comment by alltheseas** [comment]
You are right. Probably doesnt belong in nostrability. Let me think where is better.

**Comment by fabianfabian** [comment]
I used to have a small list of emojis for counting positive, but then removed it because it wasn't complete enough, but with all the discussion around #88 and #89 I think its better to bring it back and the list here seems like a good starting point. Even if we don't have a complete list, or maybe the list is only correct 90% of the time, its still more useful to use these signals to feed algorithms than not using them at all.

**Comment by vitorpamplona** [comment]
> where is that from, looks great @vitorpamplona

Nature: https://www.nature.com/articles/s41598-021-04357-7
